### ISSUE TITLE
django-defender installation failed

### ISSUE THREAD

**Issue by adrian-zumbler** [kencochrane/django-defender#109]
I tray to install django-defender but I receive the following error

$ pip install django-defender
Collecting django-defender
  Using cached django_defender-0.5.1-py2-none-any.whl
Collecting mockredispy<3.0,>=2.9.0.11 (from django-defender)
Exception:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pip/download.py", line 809, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pip/download.py", line 715, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pip/utils/__init__.py", line 599, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pip/utils/__init__.py", line 484, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file

**Comment by kencochrane** [comment]
Are you having this issue with just django-defender, or with other packages as well?

The reason why I ask is because it doesn't look like a defender error, and no one else has reported an issue.

**Comment by kencochrane** [comment]
@adrian-zumbler any update on this issue? Does it still not work for you?

**Comment by kencochrane** [comment]
closing due to lack of information, feel free to reopen if still an issue.
