### ISSUE TITLE
Django 1.11 - Decorator for class-based views in urls.py

### ISSUE THREAD

**Issue by felixkohtz** [kencochrane/django-defender#94]
Django 1.11.4

I am using class-based views for my login.

From the Django docs - "The login function-based view should be replaced by the class-based": https://docs.djangoproject.com/en/1.11/topics/auth/default/#django.contrib.auth.views.LoginView

Since i can't find a documentation or figure out how to decorate a class-based view, how would i do it in urls.py ?

urls.py

```
from defender.decorators import watch_login
urlpatterns = [
...
url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
]
```

Regards

**Comment by Temeez** [comment]
It would go like this.
```
from defender.decorators import watch_login
urlpatterns = [
...
url(r'^login/$', watch_login(auth_views.LoginView.as_view()), name='login'),
]
```

**Comment by felixkohtz** [comment]
Here is the traceback when i try to implement it like this:

```
Request Method: GET
Request URL: http://127.0.0.1:8000/login/?next=/

Django Version: 1.11.4
Python Version: 3.5.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'wiki',
 'printer',
 'ckeditor',
 'ckeditor_uploader',
 'crispy_forms',
 'defender']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "/opt/django_uhd_wiki/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/opt/django_uhd_wiki/lib/python3.5/site-packages/django/utils/deprecation.py" in __call__
  142.             response = self.process_response(request, response)

File "/opt/django_uhd_wiki/lib/python3.5/site-packages/django/middleware/clickjacking.py" in process_response
  32.         if response.get('X-Frame-Options') is not None:

Exception Type: AttributeError at /login/
Exception Value: 'function' object has no attribute 'get'

```

**Comment by felixkohtz** [comment]
Traceback when i try to implement without class-based

`url(r'^login/$', watch_login(auth_views.login), name='login'),`

```
Request Method: GET
Request URL: http://127.0.0.1:8000/login/

Django Version: 1.11.4
Python Version: 3.5.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'wiki',
 'printer',
 'ckeditor',
 'ckeditor_uploader',
 'crispy_forms',
 'defender']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "/opt/django_uhd_wiki/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/opt/django_uhd_wiki/lib/python3.5/site-packages/django/utils/deprecation.py" in __call__
  142.             response = self.process_response(request, response)

File "/opt/django_uhd_wiki/lib/python3.5/site-packages/django/middleware/clickjacking.py" in process_response
  32.         if response.get('X-Frame-Options') is not None:

Exception Type: AttributeError at /login/
Exception Value: 'function' object has no attribute 'get'
```

am i doing something wrong or is this django 1.11.4 related?

**Comment by kencochrane** [comment]
@felixkohtz I'm not sure, I'm not using it with Django 1.11 yet. It might be something that changed in 1.11 that is causing this. 

In django 1.11 they changed from function based login/logout and instead are using Class based ones, possibly related.

From https://docs.djangoproject.com/en/1.11/releases/1.11/ 
> The LoginView and LogoutView class-based views supersede the deprecated login() and logout() function-based views.

> contrib.auth’s login() and logout() function-based views are deprecated in favor of new class-based views LoginView and LogoutView.

**Comment by MattBlack85** [comment]
Are you using the latest version of defender @felixkohtz? If yes then the decorator itself expects 2 args that are a status code and a message, you are passing a function. Try to use it like:
`watch_login()LoginView.as_view()`

**Comment by MattBlack85** [comment]
btw if you are using the middleware the Django LoginView is already decorated https://github.com/kencochrane/django-defender/blob/master/defender/middleware.py#L27

**Comment by felixkohtz** [comment]
> Are you using the latest version of defender @felixkohtz?

```
$ pip install --upgrade django-defender
$ pip freeze
```
django-defender==0.5.0

> Try to use it like:
> watch_login()LoginView.as_view()

watch_login()LoginView.as_view()

changed to 

url(r'^login/$', watch_login()auth_views.LoginView.as_view(), name='login'),

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7feeca7fd158>
Traceback (most recent call last):
  File "/opt/django_uhd_wiki/lib/python3.5/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/opt/django_uhd_wiki/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/opt/django_uhd_wiki/lib/python3.5/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/opt/django_uhd_wiki/lib/python3.5/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/opt/django_uhd_wiki/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/opt/django_uhd_wiki/lib/python3.5/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/opt/django_uhd_wiki/lib/python3.5/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/opt/django_uhd_wiki/lib/python3.5/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/opt/django_uhd_wiki/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/django_uhd_wiki/lib/python3.5/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/django_uhd_wiki/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/django_uhd_wiki/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/django_uhd_wiki/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 669, in exec_module
  File "<frozen importlib._bootstrap_external>", line 775, in get_code
  File "<frozen importlib._bootstrap_external>", line 735, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/django_uhd_wiki/uhd/uhd/urls.py", line 30
    url(r'^login/$', watch_login()auth_views.LoginView.as_view(), name='login'),
                                           ^
SyntaxError: invalid syntax

```

> btw if you are using the middleware the Django LoginView is already decorated 

To use the middleware i had to use pip with git+ to clone the repository.
`pip install --upgrade git+https://github.com/kencochrane/django-defender.git`

Added
`'defender.middleware.FailedLoginMiddleware',`
to settings.py

With the middleware it is working, so i think this can be closed.

Thanks!

**Comment by kencochrane** [comment]
Thanks for the reminder, I should push out a 0.5.1 release with what is currently on master. I haven't heard any complaints so it is probably good to go.

**Comment by kencochrane** [comment]
@felixkohtz FYI 0.5.1 has been pushed to pypi.
